### ISSUE TITLE
Lunch checklist

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/impreuna-pentru-sanatate#300]
- [x]  remove htacces password
- [x]  increase db instance
- [x]  increase webserver instance and more as baseline.
- [x]  Cleanup database
- [x]  upgrade php-fpm settings for high traffic
- [x]  Load test
